### ISSUE TITLE
Project cleanups

### ISSUE THREAD

**Issue by siwinski** [release-monitoring/anitya#315]
I have several projects in https://release-monitoring.org/ that require some cleaning up.  I figured it would be better to combine them all into one ticket instead of smaller individual tickets.

Remove versions that are in other dual-installable packages (regex'es have been updated):
- [x] [Guzzle (v5) / php-guzzlehttp-guzzle](https://release-monitoring.org/project/3580/): Remove all `6.*` versions
- [x] [php-egulias-email-validator](https://release-monitoring.org/project/6206/): Remove all `2.*` versions
- [x] [php-google-apiclient](https://release-monitoring.org/project/3577/): Remove all `2.*` versions
- [x] [php-JsonSchema](https://release-monitoring.org/project/3584/): Remove all `2.*` versions
- [x] [php-PHPParser](https://release-monitoring.org/project/3606/): Remove all `2.*` versions
- [x] [Silex / php-silex](https://release-monitoring.org/project/6905/): Remove all `2.*` versions

Delete the following projects that only have Fedora mappings and have been retired in Fedora:
- [ ] [php-d11wtq-boris](https://release-monitoring.org/project/6466/)
- [ ] [php-JMSParser](https://release-monitoring.org/project/3582/)
- [ ] [php-Metadata](https://release-monitoring.org/project/3586/)
- [ ] [php-PhpCollection](https://release-monitoring.org/project/3604/)
- [ ] [php-PhpOption](https://release-monitoring.org/project/3605/)

**Comment by pypingou** [comment]
> Remove versions that are in other dual-installable packages (regex'es have been updated)

I'll do that next week

 > Delete the following projects that only have Fedora mappings and have been retired in Fedora:

That I won't do, I don't delete projects because Fedora stopped shipping them

**Comment by pypingou** [comment]
>  php-egulias-email-validator: Remove all 2.* versions
Looking upstream, the latest version seems to be 2.1.0 and there is nothing specifying that anitya tracks only the 1.x versions

**Comment by siwinski** [comment]
> I'll do that next week

Thanks!

> That I won't do, I don't delete projects because Fedora stopped shipping them

OK

> Looking upstream, the latest version seems to be 2.1.0 and there is nothing specifying that anitya tracks only the 1.x versions

The backend is set to `cusom` and the regex is `\/releases\/tag\/v?(1\.\d+\.\d+)` -- https://release-monitoring.org/project/6206/edit

**Comment by pypingou** [comment]
I'd like the v2 project to be added

**Comment by pypingou** [comment]
Done for the first list :)

**Comment by Zlopez** [comment]
@pypingou 
Can I close this issue or is there something still missing?
