### ISSUE TITLE
FAS login into staging error 500

### ISSUE THREAD

**Issue by abitrolly** [release-monitoring/anitya#565]
When logging with FAS to https://release-monitoring.app.os.stg.fedoraproject.org/ it fails with error 500 on https://release-monitoring.app.os.stg.fedoraproject.org/complete/fedora/

**Comment by Zlopez** [comment]
I'm adding error message from Firefox:
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

**Comment by Zlopez** [comment]
@abitrolly 
I tested this on my local deployment and I don't have this issue.
I'm using latest commit, so maybe this is already fixed.

**Comment by Zlopez** [comment]
There was some issue with database setup, it's fixed now.
This issue can be closed

**Comment by abitrolly** [comment]
I am still getting 500 error trying to login with FAS to staging. Does it work for you?

**Comment by Zlopez** [comment]
Yes, I'm actually logged in using FAS account.

**Comment by Zlopez** [comment]
@abitrolly 
Do you still have the issue with logging in?

**Comment by abitrolly** [comment]
@Zlopez yes, I still have the issue with logging in to https://release-monitoring.app.os.stg.fedoraproject.org/

**Comment by Zlopez** [comment]
@abitrolly 
Could you try https://stg.release-monitoring.org/
Because this should be the correct staging url.

**Comment by abitrolly** [comment]
Doesn't work too - https://stg.release-monitoring.org/complete/fedora/?janrain_nonce=2018-08 ... gives 500.

**Comment by Zlopez** [comment]
This is weird, I logged in without issue.
Do you have this issue in different application?
Could you post here, what is printed in console?

**Comment by abitrolly** [comment]
In JavaScript console? Nothing there.

**Comment by abitrolly** [comment]
No issues with other apps.

**Comment by Zlopez** [comment]
Ok, I was able to check the logs and found the issue.
I'm not sure why this is happening, but according to the logs, Anitya is trying to insert your user in the database even if your user already exists.
I will check the db schema, maybe this is only caused by bad constraint or unique key in user database.

**Comment by abitrolly** [comment]
Probably something is not saved into DB for new users.

**Comment by jeremycline** [comment]
At some point I believe there were permissions issues on the database where the anitya user didn't have write access to some tables (possibly the social_auth tables?). I wonder if things aren't covered in a single transaction and it got part-way through making an account.

The _other_ possibility is that it initially failed to log in due to permissions, then the Fedora ID server got changed from production to staging and now there's a uniqueness constraint violation (because we currently don't support logging in with the same email from different identity providers).

**Comment by Zlopez** [comment]
@jeremycline 
So it should be enough to just delete the user from db? And let the Anitya create it again on next login?

**Comment by jeremycline** [comment]
@Zlopez yes, I think so

**Comment by Zlopez** [comment]
@jeremycline 
Do you have access to do this?
I'm not sure if this could be done by user with admin role or we need to do this manually in the database.

**Comment by jeremycline** [comment]
I do not, unfortunately. You could ask the admins to drop the current stage and resync it from production, since these tables are new in 0.12 and will be recreated by the migrations.

**Comment by Zlopez** [comment]
Are you sure that this wouldn't have any impact on current staging if there are new tables?

**Comment by jeremycline** [comment]
The migrations will need to be re-run. If it's still set up the way I did it, it's a pre-deployment job so you'll just need to kick off a new deployment in Openshift

**Comment by abitrolly** [comment]
Shouldn't Anitya recover from such errors gracefully? Like rolling back the transaction with the explanation that "user already exists in table A but don't have record in table B". Dropping DB is like postponing the problem.

@Zlopez can you post exact error message and some refs to tables here just for the reference?

**Comment by Zlopez** [comment]
@abitrolly 
Sorry, I thought I already did this (I just changed the e-mail and username):
```
[2018-08-16 15:10:44,946] ERROR in app: Exception on /complete/fedora/ [GET]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "ix_users_email"
DETAIL:  Key (email)=(user@mail.org) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/social_flask/utils.py", line 43, in wrapper
    return func(backend, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_flask/routes.py", line 23, in complete
    *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_core/actions.py", line 41, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_core/backends/open_id.py", line 177, in auth_complete
    *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_core/strategy.py", line 159, in authenticate
    return backend.authenticate(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_core/backends/base.py", line 113, in run_pipeline
    result = func(*args, **out) or {}
  File "/usr/lib/python3.6/site-packages/social_core/pipeline/user.py", line 75, in create_user
    'user': strategy.create_user(**fields)
  File "/usr/lib/python3.6/site-packages/social_core/strategy.py", line 53, in create_user
    return self.storage.user.create_user(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_sqlalchemy/storage.py", line 144, in create_user
    return cls._new_instance(cls.user_model(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/social_sqlalchemy/storage.py", line 58, in _new_instance
    return cls._save_instance(model(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/social_sqlalchemy/storage.py", line 64, in _save_instance
   cls._session().commit()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "ix_users_email"
DETAIL:  Key (email)=(user@mail.org) already exists.
 [SQL: 'INSERT INTO users (id, email, username, active) VALUES (%(id)s, %(email)s, %(username)s, %(active)s)'] [parameters: {'id': UUID('4dc1674f-8d6f-4580-b40c-e120213b47a2'), 'email': 'user@mail.org', 'username': 'user', 'active': True}] (Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1518, in handle_user_exception
    return handler(e)
  File "/usr/local/lib/python3.6/site-packages/anitya/app.py", line 147, in integrity_error_handler
    social_auth_user = other_user.social_auth.filter_by(user_id=other_user.id).one()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2953, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

**Comment by Zlopez** [comment]
When thinking about it, this could be possibly solved by modifying the current user entry when e-mail is the same instead of trying to insert it again if anything changed.
The authentication of the user is done by third party after all.

**Comment by Zlopez** [comment]
Ok, so the best course of action is probably to sync production db with staging db.

**Comment by abitrolly** [comment]
Improving error message and not crashing will help get problem description right. If a user was already registered with other provider, it would be nice to see what is this provider. After that it will be possible to decide on best recovery strategy.

For example, it can be email validation. Many services allow to add new login methods to *user account* if user can validate email. If email is the key for user accounts, then maybe authentication services to another table with properties like `needs_validation`. For external service like Fedora FAS validation is already done on their side and can be skipped. Even if the service is not trusted, it can be just a source of user data that needs to be validated.

In any case this needs good algorithm description for future reference to cover what happens when user registers account, if it is a new `user_account` record or just a mirror of existing record elsewhere, what happens if remote record expires, if user changes email, etc.

**Comment by Zlopez** [comment]
There should be at least error message instead of 500 - Internal error.
Something like: "This e-mail is already registered."

I need to go through the current implementation to see how it works. I didn't implemented this one and I don't have much experience with third party authentication. So I first need to look at it more closely before I can say what could be done with this.

**Comment by Zlopez** [comment]
I was able to find the root of this issue.
The exception is thrown here https://github.com/release-monitoring/anitya/blob/fc2aead9be5b9147108ff667a4ec3ece62b52130/anitya/app.py#L147

The user_id doesn't exists in social_auth table, but we have it in our local user database.
Maybe in this case it is save to delete the user in our database, it is not in social_auth table anyway.
And just print some error to user: "Error happened during authentication of user, try it again."

@jeremycline What do you think?

**Comment by jeremycline** [comment]
Oh that's interesting. Ideally those two rows are created in the same transaction and either both are added or neither are added. Making sure that happens would be the best fix, and leave that handler as-is (because the assumption it's making is then safe). It may be a bit tricky to make that work right with social_auth, I'm not sure.

**Comment by Zlopez** [comment]
The social_auth is not that flexible, I will see if you can handle it that way.
Maybe some SQLAlchemy event could check this.

**Comment by Zlopez** [comment]
This is done in one request, but probably not checked before commit.
However the sequence diagram will be good addition to Anitya documentation.
I will look if there is any tool that can generate it automatically.

**Comment by abitrolly** [comment]
@Zlopez it is possible to generate sequence diagram from the text description - http://blockdiag.com/en/seqdiag/index.html - or do you mean generating it from Python code?

**Comment by Zlopez** [comment]
I wanted to generate it directly from the code, but didn't find any tool, that can do it.

**Comment by nqb** [comment]
Some Python modules that uses GraphViz ?

**Comment by Zlopez** [comment]
@nqb 
I didn't found any, that will do it automatically.

BTW I created another issue for sequence diagram https://github.com/release-monitoring/anitya/issues/640.
