### ISSUE TITLE
Upstream PyPI release notification is late

### ISSUE THREAD

**Issue by gsauthof** [release-monitoring/anitya#612]
In my https://apps.fedoraproject.org/notifications/ settings I configured a filter to get notified of new releases for some PyPI project:

    filter name: upstream-releases
        -> sent to email
    Rules  defined for this filter:
        anything regarding a particular 'upstream project': asyncssh, ...

For the last asyncssh release I got notified - but 3 days late.

That means:

- 2018-09-08 - asyncssh release according to PyPI
- 2018-09-08 21:48 +00:00 libraries.io release notification (configured this as a backup)
- 2018-09-11 00:17 +00:00 fedoraproject.org release notification

So this notification lag within the fedora notification system seems a bit excessive.

Btw, when I go into the settings for this notification filter, there is a 'Searching for example for messages that match this filter' headline followed by an in-progress animation - which never finishes (i.e. no results are displayed).

**Comment by Zlopez** [comment]
This is probably cause by this issue https://github.com/release-monitoring/anitya/issues/605
When the new version 0.13.0 will be released (currently in staging https://stg.release-monitoring.org) this should be solved.

**Comment by gsauthof** [comment]
When was 0.13.0 released?

Notifications still don't work. Current examples:

- [asyncssh](https://pypi.org/project/asyncssh/#history) - last release on 2018-11-27 - no notification via anitya so far
- [img2pdf](https://pypi.org/project/img2pdf/#history) - last release on 2018-11-20 - no notification via anitya so far
